version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pix-postgres
    restart: always
    environment:
      POSTGRES_DB: pixdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"